export const MOTS = [
  { name: "Professeur", categorie: "L'ÉCOLE – LA CLASSE – L'INSTRUCTION" },
  { name: "Élève", categorie: "L'ÉCOLE – LA CLASSE – L'INSTRUCTION" },
  { name: "Cahier", categorie: "L'ÉCOLE – LA CLASSE – L'INSTRUCTION" },
  { name: "Crayon", categorie: "L'ÉCOLE – LA CLASSE – L'INSTRUCTION" },
  { name: "Bureau", categorie: "L'ÉCOLE – LA CLASSE – L'INSTRUCTION" },
  { name: "Tableau", categorie: "L'ÉCOLE – LA CLASSE – L'INSTRUCTION" },
  { name: "Livre", categorie: "L'ÉCOLE – LA CLASSE – L'INSTRUCTION" },
  { name: "Règle", categorie: "L'ÉCOLE – LA CLASSE – L'INSTRUCTION" },
  { name: "École", categorie: "L'ÉCOLE – LA CLASSE – L'INSTRUCTION" },
  { name: "Classe", categorie: "L'ÉCOLE – LA CLASSE – L'INSTRUCTION" },
  { name: "Apprentissage", categorie: "L'ÉCOLE – LA CLASSE – L'INSTRUCTION" },
  { name: "Lecture", categorie: "L'ÉCOLE – LA CLASSE – L'INSTRUCTION" },
  { name: "Écriture", categorie: "L'ÉCOLE – LA CLASSE – L'INSTRUCTION" },
  { name: "Mathématiques", categorie: "L'ÉCOLE – LA CLASSE – L'INSTRUCTION" },
  { name: "Exercice", categorie: "L'ÉCOLE – LA CLASSE – L'INSTRUCTION" },
  { name: "Montagne", categorie: "PAYSAGES – CLIMAT – FORMES" },
  { name: "Plage", categorie: "PAYSAGES – CLIMAT – FORMES" },
  { name: "Lac", categorie: "PAYSAGES – CLIMAT – FORMES" },
  { name: "Forêt", categorie: "PAYSAGES – CLIMAT – FORMES" },
  { name: "Nuage", categorie: "PAYSAGES – CLIMAT – FORMES" },
  { name: "Soleil", categorie: "PAYSAGES – CLIMAT – FORMES" },
  { name: "Pluie", categorie: "PAYSAGES – CLIMAT – FORMES" },
  { name: "Vent", categorie: "PAYSAGES – CLIMAT – FORMES" },
  { name: "Neige", categorie: "PAYSAGES – CLIMAT – FORMES" },
  { name: "Étoile", categorie: "PAYSAGES – CLIMAT – FORMES" },
  { name: "Ciel", categorie: "PAYSAGES – CLIMAT – FORMES" },
  { name: "Colline", categorie: "PAYSAGES – CLIMAT – FORMES" },
  { name: "Rivière", categorie: "PAYSAGES – CLIMAT – FORMES" },
  { name: "Vague", categorie: "PAYSAGES – CLIMAT – FORMES" },
  { name: "Arbre", categorie: "PAYSAGES – CLIMAT – FORMES" },
  { name: "Gentillesse", categorie: "QUALITÉS ET DÉFAUTS" },
  { name: "Courage", categorie: "QUALITÉS ET DÉFAUTS" },
  { name: "Patience", categorie: "QUALITÉS ET DÉFAUTS" },
  { name: "Honnêteté", categorie: "QUALITÉS ET DÉFAUTS" },
  { name: "Générosité", categorie: "QUALITÉS ET DÉFAUTS" },
  { name: "Amabilité", categorie: "QUALITÉS ET DÉFAUTS" },
  { name: "Sincérité", categorie: "QUALITÉS ET DÉFAUTS" },
  { name: "Humilité", categorie: "QUALITÉS ET DÉFAUTS" },
  { name: "Curiosité", categorie: "QUALITÉS ET DÉFAUTS" },
  { name: "Créativité", categorie: "QUALITÉS ET DÉFAUTS" },
  { name: "Jalousie", categorie: "QUALITÉS ET DÉFAUTS" },
  { name: "Égoïsme", categorie: "QUALITÉS ET DÉFAUTS" },
  { name: "Impatience", categorie: "QUALITÉS ET DÉFAUTS" },
  { name: "Rancune", categorie: "QUALITÉS ET DÉFAUTS" },
  { name: "Arrogance", categorie: "QUALITÉS ET DÉFAUTS" },
  { name: "Addition", categorie: "CALCUL ET MESURES" },
  { name: "Soustraction", categorie: "CALCUL ET MESURES" },
  { name: "Multiplication", categorie: "CALCUL ET MESURES" },
  { name: "Division", categorie: "CALCUL ET MESURES" },
  { name: "Nombre", categorie: "CALCUL ET MESURES" },
  { name: "Mesure", categorie: "CALCUL ET MESURES" },
  { name: "Longueur", categorie: "CALCUL ET MESURES" },
  { name: "Poids", categorie: "CALCUL ET MESURES" },
  { name: "Temps", categorie: "CALCUL ET MESURES" },
  { name: "Volume", categorie: "CALCUL ET MESURES" },
  { name: "Mètre", categorie: "CALCUL ET MESURES" },
  { name: "Gramme", categorie: "CALCUL ET MESURES" },
  { name: "Seconde", categorie: "CALCUL ET MESURES" },
  { name: "Litre", categorie: "CALCUL ET MESURES" },
  { name: "Centimètre", categorie: "CALCUL ET MESURES" },
  { name: "Pomme", categorie: "LES ALIMENTS – LES BOISSONS- LES REPAS" },
  { name: "Pain", categorie: "LES ALIMENTS – LES BOISSONS- LES REPAS" },
  { name: "Lait", categorie: "LES ALIMENTS – LES BOISSONS- LES REPAS" },
  { name: "Carotte", categorie: "LES ALIMENTS – LES BOISSONS- LES REPAS" },
  { name: "Banane", categorie: "LES ALIMENTS – LES BOISSONS- LES REPAS" },
  { name: "Fromage", categorie: "LES ALIMENTS – LES BOISSONS- LES REPAS" },
  { name: "Fraise", categorie: "LES ALIMENTS – LES BOISSONS- LES REPAS" },
  { name: "Poulet", categorie: "LES ALIMENTS – LES BOISSONS- LES REPAS" },
  { name: "Tomate", categorie: "LES ALIMENTS – LES BOISSONS- LES REPAS" },
  { name: "Chocolat", categorie: "LES ALIMENTS – LES BOISSONS- LES REPAS" },
  { name: "Eau", categorie: "LES ALIMENTS – LES BOISSONS- LES REPAS" },
  { name: "Jus", categorie: "LES ALIMENTS – LES BOISSONS- LES REPAS" },
  { name: "Déjeuner", categorie: "LES ALIMENTS – LES BOISSONS- LES REPAS" },
  { name: "Dîner", categorie: "LES ALIMENTS – LES BOISSONS- LES REPAS" },
  { name: "Goûter", categorie: "LES ALIMENTS – LES BOISSONS- LES REPAS" },
  { name: "Pizza", categorie: "LES ALIMENTS – LES BOISSONS- LES REPAS" },
  { name: "Yaourt", categorie: "LES ALIMENTS – LES BOISSONS- LES REPAS" },
  { name: "Glace", categorie: "LES ALIMENTS – LES BOISSONS- LES REPAS" },
  { name: "Céréales", categorie: "LES ALIMENTS – LES BOISSONS- LES REPAS" },
  { name: "Frites", categorie: "LES ALIMENTS – LES BOISSONS- LES REPAS" },
  { name: "Omelette", categorie: "LES ALIMENTS – LES BOISSONS- LES REPAS" },
  { name: "Crêpe", categorie: "LES ALIMENTS – LES BOISSONS- LES REPAS" },
  { name: "Hamburger", categorie: "LES ALIMENTS – LES BOISSONS- LES REPAS" },
  { name: "Pastèque", categorie: "LES ALIMENTS – LES BOISSONS- LES REPAS" },
  { name: "Salade", categorie: "LES ALIMENTS – LES BOISSONS- LES REPAS" },
  { name: "Bonbon", categorie: "LES ALIMENTS – LES BOISSONS- LES REPAS" },
  { name: "Légumes", categorie: "LES ALIMENTS – LES BOISSONS- LES REPAS" },
  { name: "Sandwich", categorie: "LES ALIMENTS – LES BOISSONS- LES REPAS" },
  { name: "Tête", categorie: "LE CORPS HUMAIN" },
  { name: "Bras", categorie: "LE CORPS HUMAIN" },
  { name: "Jambes", categorie: "LE CORPS HUMAIN" },
  { name: "Yeux", categorie: "LE CORPS HUMAIN" },
  { name: "Oreilles", categorie: "LE CORPS HUMAIN" },
  { name: "Bouche", categorie: "LE CORPS HUMAIN" },
  { name: "Nez", categorie: "LE CORPS HUMAIN" },
  { name: "Cheveux", categorie: "LE CORPS HUMAIN" },
  { name: "Mains", categorie: "LE CORPS HUMAIN" },
  { name: "Pieds", categorie: "LE CORPS HUMAIN" },
  { name: "Coeur", categorie: "LE CORPS HUMAIN" },
  { name: "Estomac", categorie: "LE CORPS HUMAIN" },
  { name: "Peau", categorie: "LE CORPS HUMAIN" },
  { name: "Os", categorie: "LE CORPS HUMAIN" },
  { name: "Doigts", categorie: "LE CORPS HUMAIN" },
  { name: "Vue", categorie: "LES SENS – LA VOLONTE – L'INTELLIGENCE" },
  { name: "Ouïe", categorie: "LES SENS – LA VOLONTE – L'INTELLIGENCE" },
  { name: "Odorat", categorie: "LES SENS – LA VOLONTE – L'INTELLIGENCE" },
  { name: "Goût", categorie: "LES SENS – LA VOLONTE – L'INTELLIGENCE" },
  { name: "Toucher", categorie: "LES SENS – LA VOLONTE – L'INTELLIGENCE" },
  { name: "Volonté", categorie: "LES SENS – LA VOLONTE – L'INTELLIGENCE" },
  { name: "Intelligence", categorie: "LES SENS – LA VOLONTE – L'INTELLIGENCE" },
  { name: "Mémoire", categorie: "LES SENS – LA VOLONTE – L'INTELLIGENCE" },
  { name: "Raisonnement", categorie: "LES SENS – LA VOLONTE – L'INTELLIGENCE" },
  { name: "Créativité", categorie: "LES SENS – LA VOLONTE – L'INTELLIGENCE" },
  { name: "Motivation", categorie: "LES SENS – LA VOLONTE – L'INTELLIGENCE" },
  {
    name: "Concentration",
    categorie: "LES SENS – LA VOLONTE – L'INTELLIGENCE",
  },
  { name: "Curiosité", categorie: "LES SENS – LA VOLONTE – L'INTELLIGENCE" },
  { name: "Réflexion", categorie: "LES SENS – LA VOLONTE – L'INTELLIGENCE" },
  { name: "Imagination", categorie: "LES SENS – LA VOLONTE – L'INTELLIGENCE" },
  { name: "Chaise", categorie: "L'INTÉRIEUR ET LE MOBILIER" },
  { name: "Table", categorie: "L'INTÉRIEUR ET LE MOBILIER" },
  { name: "Lit", categorie: "L'INTÉRIEUR ET LE MOBILIER" },
  { name: "Canapé", categorie: "L'INTÉRIEUR ET LE MOBILIER" },
  { name: "Armoire", categorie: "L'INTÉRIEUR ET LE MOBILIER" },
  { name: "Fenêtre", categorie: "L'INTÉRIEUR ET LE MOBILIER" },
  { name: "Porte", categorie: "L'INTÉRIEUR ET LE MOBILIER" },
  { name: "Télévision", categorie: "L'INTÉRIEUR ET LE MOBILIER" },
  { name: "Lampe", categorie: "L'INTÉRIEUR ET LE MOBILIER" },
  { name: "Bureau", categorie: "L'INTÉRIEUR ET LE MOBILIER" },
  { name: "Étagère", categorie: "L'INTÉRIEUR ET LE MOBILIER" },
  { name: "Coussin", categorie: "L'INTÉRIEUR ET LE MOBILIER" },
  { name: "Miroir", categorie: "L'INTÉRIEUR ET LE MOBILIER" },
  { name: "Tapis", categorie: "L'INTÉRIEUR ET LE MOBILIER" },
  { name: "Penderie", categorie: "L'INTÉRIEUR ET LE MOBILIER" },
  { name: "Usine", categorie: "L'INDUSTRIE ET LE TRAVAIL" },
  { name: "Ouvrier", categorie: "L'INDUSTRIE ET LE TRAVAIL" },
  { name: "Machine", categorie: "L'INDUSTRIE ET LE TRAVAIL" },
  { name: "Travailleur", categorie: "L'INDUSTRIE ET LE TRAVAIL" },
  { name: "Production", categorie: "L'INDUSTRIE ET LE TRAVAIL" },
  { name: "Fabrication", categorie: "L'INDUSTRIE ET LE TRAVAIL" },
  { name: "Industrie", categorie: "L'INDUSTRIE ET LE TRAVAIL" },
  { name: "Employé", categorie: "L'INDUSTRIE ET LE TRAVAIL" },
  { name: "Bureau", categorie: "L'INDUSTRIE ET LE TRAVAIL" },
  { name: "Économie", categorie: "L'INDUSTRIE ET LE TRAVAIL" },
  { name: "Production", categorie: "L'INDUSTRIE ET LE TRAVAIL" },
  { name: "Travail", categorie: "L'INDUSTRIE ET LE TRAVAIL" },
  { name: "Carrière", categorie: "L'INDUSTRIE ET LE TRAVAIL" },
  { name: "Entrepôt", categorie: "L'INDUSTRIE ET LE TRAVAIL" },
  { name: "Secteur", categorie: "L'INDUSTRIE ET LE TRAVAIL" },
  { name: "Peinture", categorie: "LES ARTS" },
  { name: "Musique", categorie: "LES ARTS" },
  { name: "Danse", categorie: "LES ARTS" },
  { name: "Sculpture", categorie: "LES ARTS" },
  { name: "Théâtre", categorie: "LES ARTS" },
  { name: "Cinéma", categorie: "LES ARTS" },
  { name: "Poésie", categorie: "LES ARTS" },
  { name: "Photographie", categorie: "LES ARTS" },
  { name: "Architecture", categorie: "LES ARTS" },
  { name: "Dessin", categorie: "LES ARTS" },
  { name: "Design", categorie: "LES ARTS" },
  { name: "Mode", categorie: "LES ARTS" },
  { name: "Artisanat", categorie: "LES ARTS" },
  { name: "Cirque", categorie: "LES ARTS" },
  { name: "Opéra", categorie: "LES ARTS" },
  { name: "Ferme", categorie: "L'AGRICULTURE" },
  { name: "Champ", categorie: "L'AGRICULTURE" },
  { name: "Tracteur", categorie: "L'AGRICULTURE" },
  { name: "Cultures", categorie: "L'AGRICULTURE" },
  { name: "Vache", categorie: "L'AGRICULTURE" },
  { name: "Poule", categorie: "L'AGRICULTURE" },
  { name: "Mouton", categorie: "L'AGRICULTURE" },
  { name: "Récolte", categorie: "L'AGRICULTURE" },
  { name: "Blé", categorie: "L'AGRICULTURE" },
  { name: "Légumes", categorie: "L'AGRICULTURE" },
  { name: "Fruit", categorie: "L'AGRICULTURE" },
  { name: "Vignoble", categorie: "L'AGRICULTURE" },
  { name: "Orge", categorie: "L'AGRICULTURE" },
  { name: "Cultiver", categorie: "L'AGRICULTURE" },
  { name: "Fertilisant", categorie: "L'AGRICULTURE" },
  { name: "Pomme", categorie: "VERGER – BOIS – CHASSE - PÊCHE" },
  { name: "Poire", categorie: "VERGER – BOIS – CHASSE - PÊCHE" },
  { name: "Cerise", categorie: "VERGER – BOIS – CHASSE - PÊCHE" },
  { name: "Pêche", categorie: "VERGER – BOIS – CHASSE - PÊCHE" },
  { name: "Forêt", categorie: "VERGER – BOIS – CHASSE - PÊCHE" },
  { name: "Arbre", categorie: "VERGER – BOIS – CHASSE - PÊCHE" },
  { name: "Chasse", categorie: "VERGER – BOIS – CHASSE - PÊCHE" },
  { name: "Pêche", categorie: "VERGER – BOIS – CHASSE - PÊCHE" },
  { name: "Gibier", categorie: "VERGER – BOIS – CHASSE - PÊCHE" },
  { name: "Hameçon", categorie: "VERGER – BOIS – CHASSE - PÊCHE" },
  { name: "Fusil", categorie: "VERGER – BOIS – CHASSE - PÊCHE" },
  { name: "Bûche", categorie: "VERGER – BOIS – CHASSE - PÊCHE" },
  { name: "Sapin", categorie: "VERGER – BOIS – CHASSE - PÊCHE" },
  { name: "Truite", categorie: "VERGER – BOIS – CHASSE - PÊCHE" },
  { name: "Saumon", categorie: "VERGER – BOIS – CHASSE - PÊCHE" },
  { name: "Marcher", categorie: "GESTES ET MOUVEMENTS" },
  { name: "Courir", categorie: "GESTES ET MOUVEMENTS" },
  { name: "Sauter", categorie: "GESTES ET MOUVEMENTS" },
  { name: "Danser", categorie: "GESTES ET MOUVEMENTS" },
  { name: "Grimper", categorie: "GESTES ET MOUVEMENTS" },
  { name: "Nager", categorie: "GESTES ET MOUVEMENTS" },
  { name: "Lancer", categorie: "GESTES ET MOUVEMENTS" },
  { name: "Attraper", categorie: "GESTES ET MOUVEMENTS" },
  { name: "Pousser", categorie: "GESTES ET MOUVEMENTS" },
  { name: "Tirer", categorie: "GESTES ET MOUVEMENTS" },
  { name: "Cuisiner", categorie: "GESTES ET MOUVEMENTS" },
  { name: "Écrire", categorie: "GESTES ET MOUVEMENTS" },
  { name: "Lire", categorie: "GESTES ET MOUVEMENTS" },
  { name: "Parler", categorie: "GESTES ET MOUVEMENTS" },
  { name: "Applaudir", categorie: "GESTES ET MOUVEMENTS" },
  { name: "Passé", categorie: "ÉPOQUE – TEMPS - SAISONS" },
  { name: "Présent", categorie: "ÉPOQUE – TEMPS - SAISONS" },
  { name: "Futur", categorie: "ÉPOQUE – TEMPS - SAISONS" },
  { name: "Matin", categorie: "ÉPOQUE – TEMPS - SAISONS" },
  { name: "Saison", categorie: "ÉPOQUE – TEMPS - SAISONS" },
  { name: "Soir", categorie: "ÉPOQUE – TEMPS - SAISONS" },
  { name: "Nuit", categorie: "ÉPOQUE – TEMPS - SAISONS" },
  { name: "Printemps", categorie: "ÉPOQUE – TEMPS - SAISONS" },
  { name: "Été", categorie: "ÉPOQUE – TEMPS - SAISONS" },
  { name: "Automne", categorie: "ÉPOQUE – TEMPS - SAISONS" },
  { name: "Hiver", categorie: "ÉPOQUE – TEMPS - SAISONS" },
  { name: "Année", categorie: "ÉPOQUE – TEMPS - SAISONS" },
  { name: "Mois", categorie: "ÉPOQUE – TEMPS - SAISONS" },
  { name: "Jour", categorie: "ÉPOQUE – TEMPS - SAISONS" },
  { name: "Heure", categorie: "ÉPOQUE – TEMPS - SAISONS" },
  { name: "Chemise", categorie: "VÊTEMENTS – TOILETTE - PARURES" },
  { name: "Pantalon", categorie: "VÊTEMENTS – TOILETTE - PARURES" },
  { name: "Robe", categorie: "VÊTEMENTS – TOILETTE - PARURES" },
  { name: "Jupe", categorie: "VÊTEMENTS – TOILETTE - PARURES" },
  { name: "Chaussures", categorie: "VÊTEMENTS – TOILETTE - PARURES" },
  { name: "Chapeau", categorie: "VÊTEMENTS – TOILETTE - PARURES" },
  { name: "Manteau", categorie: "VÊTEMENTS – TOILETTE - PARURES" },
  { name: "Écharpe", categorie: "VÊTEMENTS – TOILETTE - PARURES" },
  { name: "Gants", categorie: "VÊTEMENTS – TOILETTE - PARURES" },
  { name: "Bijoux", categorie: "VÊTEMENTS – TOILETTE - PARURES" },
  { name: "Maquillage", categorie: "VÊTEMENTS – TOILETTE - PARURES" },
  { name: "Parfum", categorie: "VÊTEMENTS – TOILETTE - PARURES" },
  { name: "Dentifrice", categorie: "VÊTEMENTS – TOILETTE - PARURES" },
  { name: "Savon", categorie: "VÊTEMENTS – TOILETTE - PARURES" },
  { name: "Peigne", categorie: "VÊTEMENTS – TOILETTE - PARURES" },
  { name: "Pyjama", categorie: "VÊTEMENTS – TOILETTE - PARURES" },
  { name: "Collier", categorie: "VÊTEMENTS – TOILETTE - PARURES" },
  { name: "Bracelet", categorie: "VÊTEMENTS – TOILETTE - PARURES" },
  { name: "Couronne", categorie: "VÊTEMENTS – TOILETTE - PARURES" },
  { name: "Football", categorie: "SPORTS ET JEUX" },
  { name: "Basketball", categorie: "SPORTS ET JEUX" },
  { name: "Tennis", categorie: "SPORTS ET JEUX" },
  { name: "Golf", categorie: "SPORTS ET JEUX" },
  { name: "Natation", categorie: "SPORTS ET JEUX" },
  { name: "Athlétisme", categorie: "SPORTS ET JEUX" },
  { name: "Volleyball", categorie: "SPORTS ET JEUX" },
  { name: "Baseball", categorie: "SPORTS ET JEUX" },
  { name: "Hockey", categorie: "SPORTS ET JEUX" },
  { name: "Rugby", categorie: "SPORTS ET JEUX" },
  { name: "Échecs", categorie: "SPORTS ET JEUX" },
  { name: "Billard", categorie: "SPORTS ET JEUX" },
  { name: "Cartes", categorie: "SPORTS ET JEUX" },
  { name: "Cyclisme", categorie: "SPORTS ET JEUX" },
  { name: "Bowling", categorie: "SPORTS ET JEUX" },
  { name: "Gymnastique", categorie: "SPORTS ET JEUX" },
  { name: "Danse", categorie: "SPORTS ET JEUX" },
  { name: "Escalade", categorie: "SPORTS ET JEUX" },
  { name: "Patinage", categorie: "SPORTS ET JEUX" },
  { name: "Badminton", categorie: "SPORTS ET JEUX" },
  { name: "Boxe", categorie: "SPORTS ET JEUX" },
  { name: "Yoga", categorie: "SPORTS ET JEUX" },
  { name: "Équitation", categorie: "SPORTS ET JEUX" },
  { name: "Roller", categorie: "SPORTS ET JEUX" },
  { name: "Ski", categorie: "SPORTS ET JEUX" },
  { name: "Maison", categorie: "LA MAISON – LE BATIMENT" },
  { name: "Appartement", categorie: "LA MAISON – LE BATIMENT" },
  { name: "Chambre", categorie: "LA MAISON – LE BATIMENT" },
  { name: "Salon", categorie: "LA MAISON – LE BATIMENT" },
  { name: "Cuisine", categorie: "LA MAISON – LE BATIMENT" },
  { name: "Baignoire", categorie: "LA MAISON – LE BATIMENT" },
  { name: "Escalier", categorie: "LA MAISON – LE BATIMENT" },
  { name: "Toit", categorie: "LA MAISON – LE BATIMENT" },
  { name: "Porte", categorie: "LA MAISON – LE BATIMENT" },
  { name: "Fenêtre", categorie: "LA MAISON – LE BATIMENT" },
  { name: "Balcon", categorie: "LA MAISON – LE BATIMENT" },
  { name: "Jardin", categorie: "LA MAISON – LE BATIMENT" },
  { name: "Garage", categorie: "LA MAISON – LE BATIMENT" },
  { name: "Étage", categorie: "LA MAISON – LE BATIMENT" },
  { name: "Mur", categorie: "LA MAISON – LE BATIMENT" },
  { name: "Avion", categorie: "LES VOYAGES" },
  { name: "Train", categorie: "LES VOYAGES" },
  { name: "Voiture", categorie: "LES VOYAGES" },
  { name: "Bateau", categorie: "LES VOYAGES" },
  { name: "Bus", categorie: "LES VOYAGES" },
  { name: "Moto", categorie: "LES VOYAGES" },
  { name: "Vélo", categorie: "LES VOYAGES" },
  { name: "Randonnée", categorie: "LES VOYAGES" },
  { name: "Plage", categorie: "LES VOYAGES" },
  { name: "Montagne", categorie: "LES VOYAGES" },
  { name: "Désert", categorie: "LES VOYAGES" },
  { name: "Exploration", categorie: "LES VOYAGES" },
  { name: "Valise", categorie: "LES VOYAGES" },
  { name: "Carte", categorie: "LES VOYAGES" },
  { name: "Guide", categorie: "LES VOYAGES" },
  { name: "Chien", categorie: "LES ANIMAUX" },
  { name: "Chat", categorie: "LES ANIMAUX" },
  { name: "Oiseau", categorie: "LES ANIMAUX" },
  { name: "Lion", categorie: "LES ANIMAUX" },
  { name: "Tigre", categorie: "LES ANIMAUX" },
  { name: "Éléphant", categorie: "LES ANIMAUX" },
  { name: "Girafe", categorie: "LES ANIMAUX" },
  { name: "Singe", categorie: "LES ANIMAUX" },
  { name: "Cheval", categorie: "LES ANIMAUX" },
  { name: "Vache", categorie: "LES ANIMAUX" },
  { name: "Poule", categorie: "LES ANIMAUX" },
  { name: "Poisson", categorie: "LES ANIMAUX" },
  { name: "Requin", categorie: "LES ANIMAUX" },
  { name: "Dauphin", categorie: "LES ANIMAUX" },
  { name: "Tortue", categorie: "LES ANIMAUX" },
  { name: "Chien", categorie: "LES ANIMAUX" },
  { name: "Chat", categorie: "LES ANIMAUX" },
  { name: "Souris", categorie: "LES ANIMAUX" },
  { name: "Lapin", categorie: "LES ANIMAUX" },
  { name: "Cochon", categorie: "LES ANIMAUX" },
  { name: "Mouton", categorie: "LES ANIMAUX" },
  { name: "Ours", categorie: "LES ANIMAUX" },
  { name: "Panda", categorie: "LES ANIMAUX" },
  { name: "Grenouille", categorie: "LES ANIMAUX" },
  { name: "Papillon", categorie: "LES ANIMAUX" },
  { name: "Coccinelle", categorie: "LES ANIMAUX" },
  { name: "Araignée", categorie: "LES ANIMAUX" },
  { name: "Serpent", categorie: "LES ANIMAUX" },
  { name: "Hérisson", categorie: "LES ANIMAUX" },
  { name: "Kangourou", categorie: "LES ANIMAUX" },
  { name: "Ville", categorie: "VILLE – VILLAGE – UNIVERS - DIMENSIONS" },
  { name: "Village", categorie: "VILLE – VILLAGE – UNIVERS - DIMENSIONS" },
  { name: "Rue", categorie: "VILLE – VILLAGE – UNIVERS - DIMENSIONS" },
  { name: "Place", categorie: "VILLE – VILLAGE – UNIVERS - DIMENSIONS" },
  { name: "Bâtiment", categorie: "VILLE – VILLAGE – UNIVERS - DIMENSIONS" },
  { name: "Quartier", categorie: "VILLE – VILLAGE – UNIVERS - DIMENSIONS" },
  { name: "Monument", categorie: "VILLE – VILLAGE – UNIVERS - DIMENSIONS" },
  { name: "Église", categorie: "VILLE – VILLAGE – UNIVERS - DIMENSIONS" },
  { name: "Parc", categorie: "VILLE – VILLAGE – UNIVERS - DIMENSIONS" },
  { name: "Planète", categorie: "VILLE – VILLAGE – UNIVERS - DIMENSIONS" },
  { name: "Étoile", categorie: "VILLE – VILLAGE – UNIVERS - DIMENSIONS" },
  { name: "Univers", categorie: "VILLE – VILLAGE – UNIVERS - DIMENSIONS" },
  { name: "Largeur", categorie: "VILLE – VILLAGE – UNIVERS - DIMENSIONS" },
  { name: "Longueur", categorie: "VILLE – VILLAGE – UNIVERS - DIMENSIONS" },
  { name: "Hauteur", categorie: "VILLE – VILLAGE – UNIVERS - DIMENSIONS" },
  { name: "Eau", categorie: "EAUX – MINÉRAUX - VÉGÉTAUX" },
  { name: "Rivière", categorie: "EAUX – MINÉRAUX - VÉGÉTAUX" },
  { name: "Mer", categorie: "EAUX – MINÉRAUX - VÉGÉTAUX" },
  { name: "Océan", categorie: "EAUX – MINÉRAUX - VÉGÉTAUX" },
  { name: "Lac", categorie: "EAUX – MINÉRAUX - VÉGÉTAUX" },
  { name: "Cascade", categorie: "EAUX – MINÉRAUX - VÉGÉTAUX" },
  { name: "Montagne", categorie: "EAUX – MINÉRAUX - VÉGÉTAUX" },
  { name: "Rocher", categorie: "EAUX – MINÉRAUX - VÉGÉTAUX" },
  { name: "Diamant", categorie: "EAUX – MINÉRAUX - VÉGÉTAUX" },
  { name: "Or", categorie: "EAUX – MINÉRAUX - VÉGÉTAUX" },
  { name: "Argent", categorie: "EAUX – MINÉRAUX - VÉGÉTAUX" },
  { name: "Arbre", categorie: "EAUX – MINÉRAUX - VÉGÉTAUX" },
  { name: "Fleur", categorie: "EAUX – MINÉRAUX - VÉGÉTAUX" },
  { name: "Herbe", categorie: "EAUX – MINÉRAUX - VÉGÉTAUX" },
  { name: "Feuille", categorie: "EAUX – MINÉRAUX - VÉGÉTAUX" },
  { name: "Magasin", categorie: "LE COMMERCE" },
  { name: "Boutique", categorie: "LE COMMERCE" },
  { name: "Supermarché", categorie: "LE COMMERCE" },
  { name: "Marché", categorie: "LE COMMERCE" },
  { name: "Vente", categorie: "LE COMMERCE" },
  { name: "Achat", categorie: "LE COMMERCE" },
  { name: "Client", categorie: "LE COMMERCE" },
  { name: "Vendeur", categorie: "LE COMMERCE" },
  { name: "Produit", categorie: "LE COMMERCE" },
  { name: "Prix", categorie: "LE COMMERCE" },
  { name: "Promotion", categorie: "LE COMMERCE" },
  { name: "Publicité", categorie: "LE COMMERCE" },
  { name: "Facture", categorie: "LE COMMERCE" },
  { name: "Livraison", categorie: "LE COMMERCE" },
  { name: "Fournisseur", categorie: "LE COMMERCE" },
  { name: "Langue", categorie: "LA COMMUNICATION" },
  { name: "Parole", categorie: "LA COMMUNICATION" },
  { name: "Écriture", categorie: "LA COMMUNICATION" },
  { name: "Lettre", categorie: "LA COMMUNICATION" },
  { name: "Message", categorie: "LA COMMUNICATION" },
  { name: "Téléphone", categorie: "LA COMMUNICATION" },
  { name: "Internet", categorie: "LA COMMUNICATION" },
  { name: "Courriel", categorie: "LA COMMUNICATION" },
  { name: "Enveloppe", categorie: "LA COMMUNICATION" },
  { name: "Journal", categorie: "LA COMMUNICATION" },
  { name: "Télévision", categorie: "LA COMMUNICATION" },
  { name: "Radio", categorie: "LA COMMUNICATION" },
  { name: "Conférence", categorie: "LA COMMUNICATION" },
  { name: "Conversation", categorie: "LA COMMUNICATION" },
  { name: "Silence", categorie: "LA COMMUNICATION" },
  { name: "Bonheur", categorie: "JOIES ET PEINES" },
  { name: "Joie", categorie: "JOIES ET PEINES" },
  { name: "Rire", categorie: "JOIES ET PEINES" },
  { name: "Plaisir", categorie: "JOIES ET PEINES" },
  { name: "Sourire", categorie: "JOIES ET PEINES" },
  { name: "Amour", categorie: "JOIES ET PEINES" },
  { name: "Amitié", categorie: "JOIES ET PEINES" },
  { name: "Fête", categorie: "JOIES ET PEINES" },
  { name: "Célébration", categorie: "JOIES ET PEINES" },
  { name: "Tristesse", categorie: "JOIES ET PEINES" },
  { name: "Pleur", categorie: "JOIES ET PEINES" },
  { name: "Douleur", categorie: "JOIES ET PEINES" },
  { name: "Déception", categorie: "JOIES ET PEINES" },
  { name: "Solitude", categorie: "JOIES ET PEINES" },
  { name: "Colère", categorie: "JOIES ET PEINES" },
  { name: "Armée", categorie: "L'ARMÉE" },
  { name: "Soldat", categorie: "L'ARMÉE" },
  { name: "Officier", categorie: "L'ARMÉE" },
  { name: "Général", categorie: "L'ARMÉE" },
  { name: "Bataille", categorie: "L'ARMÉE" },
  { name: "Arme", categorie: "L'ARMÉE" },
  { name: "Canon", categorie: "L'ARMÉE" },
  { name: "Munition", categorie: "L'ARMÉE" },
  { name: "Uniforme", categorie: "L'ARMÉE" },
  { name: "Drapeau", categorie: "L'ARMÉE" },
  { name: "Honneur", categorie: "L'ARMÉE" },
  { name: "Discipline", categorie: "L'ARMÉE" },
  { name: "Entraînement", categorie: "L'ARMÉE" },
  { name: "Mission", categorie: "L'ARMÉE" },
  { name: "Victoire", categorie: "L'ARMÉE" },
  { name: "Vie", categorie: "VIE HUMAINE – MALADIES - HYGIÈNE" },
  { name: "Naissance", categorie: "VIE HUMAINE – MALADIES - HYGIÈNE" },
  { name: "Mort", categorie: "VIE HUMAINE – MALADIES - HYGIÈNE" },
  { name: "Maladie", categorie: "VIE HUMAINE – MALADIES - HYGIÈNE" },
  { name: "Santé", categorie: "VIE HUMAINE – MALADIES - HYGIÈNE" },
  { name: "Hygiène", categorie: "VIE HUMAINE – MALADIES - HYGIÈNE" },
  { name: "Médecin", categorie: "VIE HUMAINE – MALADIES - HYGIÈNE" },
  { name: "Infirmier", categorie: "VIE HUMAINE – MALADIES - HYGIÈNE" },
  { name: "Patient", categorie: "VIE HUMAINE – MALADIES - HYGIÈNE" },
  { name: "Traitement", categorie: "VIE HUMAINE – MALADIES - HYGIÈNE" },
  { name: "Vaccin", categorie: "VIE HUMAINE – MALADIES - HYGIÈNE" },
  { name: "Hôpital", categorie: "VIE HUMAINE – MALADIES - HYGIÈNE" },
  { name: "Chirurgie", categorie: "VIE HUMAINE – MALADIES - HYGIÈNE" },
  { name: "Pharmacie", categorie: "VIE HUMAINE – MALADIES - HYGIÈNE" },
  { name: "Prévention", categorie: "VIE HUMAINE – MALADIES - HYGIÈNE" },
];
